---
- hosts: all
  tasks:
    - name: Server Information
	  debug:
	    msg: Server Details "{{ ansible_architecture }} \n {{ansible_distribution}} \n {{ansible_distribution_release}} \n {{ansible_distribution_version}} \n {{ansible_hostname}} \n {{ansible_processor_cores}} \n {{ansible_product_name}}"
		
		
		
- hosts: all
  tasks:
    - name: System Information
      debug:
         msg: "{{ ansible_all_ipv4_addresses }}\n {{ ansible_bios_version }}\n {{ ansible_date_time_date }}\n {{ansible_default_ipv4}}\n {{ ansible_device_links_ids }}\n {{ ansible_distribution }}\n {{ ansible_distribution_release }} \n {{ ansible_distribution_version }} \n {{ ansible_dns_nameservers }} "